### PR TITLE
Automate the Linux BSQL install

### PR DESCRIPTION
**Pull request by Gh0sT2242**
BSQL for Linux doesn't have the greatest documentation, and most people don't know how to use Linux. I wrote a bash script that fully automates the install process. Includes all dependencies as well as updating the server/node before hand.

I have not updated the documentation.

### CODE REVIEW

**Comment by Gh0sT2242** [comment]
*sigh* Travis why are you like this
It works...
but you have the wrong directories

**Comment by Gh0sT2242** [comment]
@SpaceManiac my shit show lol

**Review by SpaceManiac — APPROVED** [review]
This script is kind of fragile-looking to me and in particular vcpkg seems unnecessary when we can get mariadb from apt, but having a bad script that works is better than having no script

**Comment by SpaceManiac** [comment]
@optimumtact I don't have merge rights on BSQL, it's in your hands now

**Pull request merged**
